export enum modeFlags{
    CUSTOM_MODE_ENABLED = 1<<0,
    TEST_ENABLED = 1<<1,
    AUTO_ENABLED = 1<<2,
    GUIDED_ENABLED = 1<<3,
    STABILIZE_ENABLED = 1<<4,
    HIL_ENABLED=1<<5,
    MANUAL_INPUT_ENABLED = 1<<6,
    SAFETY_ARMED = 1<<7
}

